### ISSUE TITLE
local variable 'title' referenced before assignment

### ISSUE THREAD

**Issue by ItzMeRadha** [Pranav-Saraswat/Testing-Alpha#2]
Vplay issue

**Comment by Pranav-Saraswat** [comment]
@ItzMeRadha I'll fix this issue tomorrow I know I also face this error

**Comment by ItzMeRadha** [comment]
Okay

**Comment by SexyShekharXD** [comment]
![Screenshot_2023_1015_143725](https://github.com/Pranav-Saraswat/Testing-Alpha/assets/121297704/b1a215ae-940f-4a8b-b5cf-89796196291c)

**Comment by guriooee** [comment]
carbon chutiya

**Comment by SexyShekharXD** [comment]
> carbon chutiya

![download (1)](https://github.com/Pranav-Saraswat/Testing-Alpha/assets/121297704/b57291d5-e7e4-4fa8-b41a-ad96a0c52e07)
