### ISSUE TITLE
Thumbnails are not Generating while deploying on heroku

### ISSUE THREAD

**Issue by KSKOP69** [Pranav-Saraswat/Testing-Alpha#6]
> Provide a general summary of the issue in the Title above.

## Expected behavior
* Tell us what should happen.

## Current behavior
* Tell us what happens instead of the expected behavior.

## Screenshot [ Optional ]
* Make a screenshot to help us understand the context more clearly.

## Possible reasons and solutions [ Optional ] 
* Suggest a fix/reason for the bug.

## Context
* How has this issue affected you? How it appeared? What are you trying to accomplish?
* Providing context helps us come up with a solution that is most useful in the real world.

## Custom values [Optional]
*  Modified any values? Added any new commands? Tweaked anything?

## Your environment
* Include as many relevant details about your environment.

## Stack trace
*  Include stack trace of the logs/console.

## Checklist
>  Go over all the following points, and put an `x` in all the boxes that apply.
- [x] I searched the [current issues](https://github.com/TeamYukki/YukkiMusicBot/issues) and the issue is not known.
- [x] I searched on Google, Steam, YouTube, Reddit and there's no fix.
- [x] I am mostly sure that the problem is related to the project and isn't my fault.

**Comment by Pranav-Saraswat** [comment]
@KSKOP69 issues bhi hindi me likhte nice

**Comment by Pranav-Saraswat** [comment]
@KSKOP69 Can you send the logs that what issue are you facing?

**Comment by Pranav-Saraswat** [comment]
@KSKOP69 I tried on heroku thumbnails are generating please dont use any fonts in Music bot name config secion otherwise you will face the error

**Comment by KSKOP69** [comment]
> @KSKOP69 I tried on heroku thumbnails are generating please dont use any fonts in Music bot name config secion otherwise you will face the error

no error showing
i tried both repos. thumbnail not generating but song is playing in vc

**Comment by KSKOP69** [comment]
[kskop69-logs-1698566924777.txt](https://github.com/Pranav-Saraswat/Testing-Alpha/files/13197524/kskop69-logs-1698566924777.txt)
