### ISSUE TITLE
Faild to process query 

### ISSUE THREAD

**Issue by ItzMeRadha** [Pranav-Saraswat/Testing-Alpha#8]
When I try to play a song with a youtube link it shows that I failed to process the query.

**Comment by ITZ-ZAID** [comment]
Please Provide Output using `yt-dlp https://youtu.be/HIWL5Sud8E0?si=RDALVqQfERKBl0FC` in your terminal/server.

**Comment by ItzMeRadha** [comment]
Solution?

**Comment by Pranav-Saraswat** [comment]
thanks for this actually I have to revert my previous commit I'll do it tomorrow

**Comment by Pranav-Saraswat** [comment]
check your ip address it works fine form my side
